### ISSUE TITLE
`<Leader>Dt` doesn't work

### ISSUE THREAD

**Issue by MVerschure** [erichlf/nvim-devcontainer-cli#10]
I have `<Leader>Dt` mapped in the plugings like:
```
{
    "<leader>Dt",
    "<CMD>DevcontainerExec source install/setup.bash && colcon --merge-install test<CR>",
    desc = "Execute test command in DevContainer",
},
```
Then running `<Leader>Dt` results in: `Devcontainer process has failed! exit_code: 126`. It might be an issue with the `source` command. The title of the window reads: `setup.bash && colcon --merge-install test`. A `<Leader>De` defined as "<CMD>DevcontainerExec<CR>" show the entire command as widow title. In fact, trying to run `source install/setup.bash` from `<Leader>De` results in the same issue

**Comment by erichlf** [comment]
But this works when you add `bash -c` and quote the command right?

**Comment by MVerschure** [comment]
Yes
