### ISSUE TITLE
Connect should bring up nvim automatically

### ISSUE THREAD

**Issue by erichlf** [erichlf/nvim-devcontainer-cli#6]
Currently, when `DevcontainerConnect` is issued, the resulting terminal window will only be a terminal window and not have `nvim` running. To mimic the behavior of `VSCode` teh resulting terminal window should be one containing `nvim`.

**Comment by ronald2wing** [comment]
Will it copy the local Neovim configs into the Docker? I only see a plain Neovim in Docker. Will it be a good idea to copy the configs into the Docker Neovim?

**Comment by ronald2wing** [comment]
Does the command install Neovim in Docker automatically if it does not already exist?

**Comment by ErichFoster-Havoc** [comment]
Your supposed to have a dotfiles install script that sets things up.

**Comment by ronald2wing** [comment]
> Your supposed to have a dotfiles install script that sets things up.

Thank you. Let me try your dotfiles repo and see how it goes.
